import numpy as np
from scipy.interpolate import RegularGridInterpolator
from scipy.ndimage import gaussian_filter1d
from lyaforecast.utils import get_dir, check_file
import sys


class Spectrograph:
    """Spectrograph model that returns pixel noise estimates from SNR data files."""

    _snr_file_dir_other = None
    _filenames_other = None

    def __init__(self, config, survey, tracer, other_tracer=None):
        """
        Parameters
        ----------
        config : configparser.ConfigParser
            Parsed configuration object.
        survey : Survey
            Survey instance providing magnitude band and pixel size.
        tracer : Tracer
            Primary Lya forest tracer whose SNR directory is read.
        other_tracer : Tracer, optional
            Second tracer for geometric-mean SNR averaging.
        """
        self.tracer = tracer
        # this is to be read from file currently.
        self._zq = None
        # survey
        self._survey = survey
        # magnitude info from survey class (g or r)
        self._band = self._survey.band
        # exposure number/time to read from file, fixed for now.
        self._file_num_exp = 4
        self._file_exp_time = 4000

        # get directory containing snr/mag files
        self._snr_file_dir = get_dir(tracer.config.get('snr-file-dir'))
        # list of filenames
        self._filenames = list(self._snr_file_dir.glob('*'))
        assert len(self._filenames) > 0, 'SNR files not found'

        if other_tracer is not None:
            # get directory containing snr/mag files
            self._snr_file_dir_other = get_dir(other_tracer.config.get('snr-file-dir'))
            # list of filenames
            self._filenames_other = list(self._snr_file_dir_other.glob('*'))
            assert len(self._filenames_other) > 0, 'SNR files not found'

        # load snr per pixel interpolater
        self._setup_desi_spectro()

    def _read_file(self, mag):
        """Read SNR as a function of (wavelength, quasar redshift) for one magnitude.

        Parameters
        ----------
        mag : float
            Apparent magnitude for which to load the SNR file.

        Returns
        -------
        lambda_obs : ndarray
            Observed wavelengths in Angstroms.
        pixel_snr : ndarray
            SNR per Angstrom, shape (n_zq, n_wave).
        """
        fname = self._snr_file_dir.joinpath(
            f'snr-{self._band}{mag}-t{str(self._file_exp_time)}-nexp{self._file_num_exp}.dat')

        print("reading magnitude {} in file {}".format(mag, fname))
        fname = check_file(fname)

        data = np.loadtxt(fname)
        lambda_obs = data[:, 0]
        pixel_snr = data[:, 1:]

        if self._snr_file_dir_other is not None:
            fname_other = self._snr_file_dir_other.joinpath(
                f'snr-{self._band}{mag}-t{str(self._file_exp_time)}-nexp{self._file_num_exp}.dat')

            print("reading magnitude {} in file {}".format(mag, fname_other))
            fname_other = check_file(fname_other)

            data_other = np.loadtxt(fname_other)
            lambda_obs_other = data_other[:, 0]
            pixel_snr_other = data_other[:, 1:]

            if pixel_snr.shape[0] > pixel_snr_other.shape[0]:
                lambda_obs = lambda_obs[:lambda_obs_other.shape[0]]
                pixel_snr = pixel_snr[:pixel_snr_other.shape[0]]
            elif pixel_snr.shape[0] < pixel_snr_other.shape[0]:
                lambda_obs_other = lambda_obs_other[:lambda_obs.shape[0]]
                pixel_snr_other = pixel_snr_other[:pixel_snr.shape[0]]

            # average the two spectrographs
            pixel_snr = np.sqrt(pixel_snr * pixel_snr_other)

        return lambda_obs, pixel_snr

    def _setup_desi_spectro(self):
        """Load all magnitude SNR files and build the 3D interpolator.

        Files are generated by desihub/desimodel/bin/desi_quicklya.py.
        """
        print('Setting up DESI spectrograph')

        self._read_desi_file_header()

        num_magnitudes = len(self._magnitudes)
        for i in range(num_magnitudes):
            m = self._magnitudes[i]
            lambda_obs_m, pixel_snr_mag = self._read_file(m)
            if i == 0:
                self._lambda_obs_m = lambda_obs_m
                num_m = num_magnitudes
                num_z = len(self._zq)
                num_wave = len(lambda_obs_m)

                self._snr_mat = np.zeros((num_m, num_z, num_wave))
            self._snr_mat[i, :, :] = pixel_snr_mag.T

        # smooth rather noisy matrix
        sigma_smooth = 10
        self._snr_mat = gaussian_filter1d(self._snr_mat, sigma_smooth, axis=2)

        # setup interpolator
        self._snr_interp = RegularGridInterpolator(
            (self._magnitudes, self._zq, self._lambda_obs_m),
            self._snr_mat, bounds_error=False, fill_value=None
        )

    def _read_desi_file_header(self):
        """Parse SNR file headers to extract magnitudes, redshifts, and band info."""
        # expect files with following header:
        # INFILE= /home/guy/software/DESI/desimodel/data/spectra/spec-lya.dat
        # BAND= r   MAG= 19.25   EXPTIME= 4000.0   NEXP= 4
        # Wave SN(z=2.0) SN(z=2.25) ...

        # find range of magnitudes
        magnitudes = []
        # quasar redshifts in file
        self.file_z_qso = None
        keys = ["INFILE", "BAND", "MAG", "EXPTIME", "NEXP"]
        for filename in self._filenames:
            head = dict()
            file = open(filename)

            for line in file.readlines():
                if line[0] != "#":
                    continue
                line = line.replace("#", "").strip()
                for k in keys:
                    if line.find(k) == 0:
                        head[k] = line.split()[-1]
                if line.find("Wave") >= 0:
                    # will bravely read the redshifts here to make sure we get it right
                    vals = line.split()
                    tmpz = []
                    for tmp in vals[1:]:
                        if tmp.find("SN(z=") < 0:
                            print("error in reading line", line)
                            print("I expect something like:")
                            print(
                                "# Wave SN(z=2.0) SN(z=2.25) SN(z=2.5) SN(z=2.75)"
                                " SN(z=3.0) SN(z=3.25) SN(z=3.5) SN(z=3.75) SN(z=4.0)"
                                " SN(z=4.25) SN(z=4.5) SN(z=4.75)"
                            )
                            sys.exit(12)
                        tmpz.append(float(tmp.replace("SN(z=", "").replace(")", "")))
                    head["Z"] = np.array(tmpz)
            file.close()

            if self._band is None:
                self._band = head["BAND"]
            else:
                assert self._band == head["BAND"]
            if self._file_num_exp is None:
                self._file_num_exp = int(head["NEXP"])
            else:
                assert self._file_num_exp == int(head["NEXP"])
            if self._zq is None:
                self._zq = head["Z"]
            else:
                assert np.all(self._zq == head["Z"])
            magnitudes.append(float(head["MAG"]))

        # quasar magnitudes in file
        self._magnitudes = np.array(magnitudes)
        self._magnitudes.sort()
        print(f'WARNING: maximum brightness capped at magnitude {self._magnitudes[0]}')

        print("In S/N files:")
        print("pass-band for magnitudes =", self._band)
        print("Nexp in file             =", self._file_num_exp)
        print("Redshifts                =", self._zq)
        print("Magnitudes               =", self._magnitudes)

    def range_zq(self):
        """Return the quasar redshift range covered by the SNR files.

        Returns
        -------
        tuple of float
            (z_min, z_max) from the loaded files.
        """
        return self.zq[0], self.zq[-1]

    def range_mag(self):
        """Return the magnitude range covered by the SNR files.

        Returns
        -------
        tuple of float
            (mag_min, mag_max) from the loaded files.
        """
        return self.mags[0], self.mags[-1]

    def range_lobs_A(self):
        """Return the observed wavelength range covered by the SNR files.

        Returns
        -------
        tuple of float
            (lambda_min, lambda_max) in Angstroms.
        """
        return self.lobs_A[0], self.lobs_A[-1]

    def get_pixel_rms_noise(self, rmag, zq, lam_obs, pix_width, num_exp=4):
        """Return the normalised noise RMS for a single pixel (inverse of S/N).

        The noise is normalised to the delta-flux field, so brighter quasars
        have smaller normalised noise.

        Parameters
        ----------
        rmag : float
            Apparent r-band magnitude of the quasar.
        zq : float
            Quasar redshift.
        lam_obs : float
            Observed wavelength of the pixel in Angstroms.
        pix_width : float
            Pixel width in Angstroms.
        num_exp : int, optional
            Number of exposures.

        Returns
        -------
        float
            Noise RMS (= 1 / S/N); returns 1e10 if out of range.
        """
        large_noise = 1e10
        if rmag > self._magnitudes[-1]:
            return large_noise
        if zq > self._zq[-1] or zq < self._zq[0]:
            print(f'zqso {zq} out of range, returning large noise')
            return large_noise

        if (self._lambda_obs_m[-1] < lam_obs) or (lam_obs < self._lambda_obs_m[0]):
            print('Forest wavelength out of bounds, returning large noise')
            return large_noise

        # if brighter than minimum magnitude, use minimum
        trmag = np.fmax(rmag, self._magnitudes[0])

        # DESI file returns S/N per Angstrom, per file_num_exp exposures
        snr_per_ang = self._snr_interp([trmag, zq, lam_obs])
        # scale with pixel width
        snr_per_exp = snr_per_ang * np.sqrt(pix_width)
        # scale with number of exposures
        snr = snr_per_exp * np.sqrt(num_exp / self._file_num_exp)
        # prevent division by zero
        snr = np.fmax(snr, 1 / large_noise)

        return 1 / snr

    def smooth_kernel_kms(self, pix_kms, res_kms, k_kms):
        """Convolution kernel in Fourier space for pixelisation and resolution.

        Square this to obtain the power spectrum smoothing kernel.

        Parameters
        ----------
        pix_kms : float
            Pixel width in km/s.
        res_kms : float
            Spectrograph resolution (1-sigma Gaussian) in km/s.
        k_kms : float or array_like
            Wavenumber in s/km.

        Returns
        -------
        float or ndarray
            Combined (sinc × Gaussian) smoothing kernel.
        """
        x = np.fmax(0.5 * k_kms * pix_kms, 1.e-10)
        x = 0.5 * k_kms * pix_kms
        pixel_kernel = np.sin(x) / x
        gauss_kernel = np.exp(-0.5 * k_kms**2 * res_kms**2)

        return pixel_kernel * gauss_kernel

    def get_snr_per_ang(self, mag, zq, lam):
        """Return the interpolated SNR per Angstrom for given (mag, z_qso, lambda).

        Parameters
        ----------
        mag : float
            Apparent magnitude.
        zq : float
            Quasar redshift.
        lam : float
            Observed wavelength in Angstroms.

        Returns
        -------
        float
            SNR per Angstrom.
        """
        return self._snr_interp([mag, zq, lam])
